[tool.briefcase]
project_name = "Table Buddy"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/tablebuddy"
license = "BSD license"
author = 'Jane Developer'
author_email = "jane@example.com"

[tool.briefcase.app.tablebuddy]
formal_name = "Table Buddy"
description = "My first application"
icon = "src/tablebuddy/resources/tablebuddy"
sources = ['src/tablebuddy']
requires = []


[tool.briefcase.app.tablebuddy.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.tablebuddy.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.tablebuddy.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.tablebuddy.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.tablebuddy.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
